### ISSUE TITLE
New text (document)

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/field-guide#36]
The CMS for the guide was getting tough to use and view changes so I started creating revised docs here: https://drive.google.com/drive/u/0/folders/1x66-iTsC0cDKTbRHecQ8W3Q7ZVxyF76a

**Comment by pjsier** [comment]
Which part of the CMS was getting difficult to use? Ideally I want to reduce the amount of docs we have floating around

**Comment by diaholliday** [comment]
Same but this doc is more a note for me so I can close the tab. 

- Changes weren't showing up immediately but I couldn't figure out how long it actually takes to update (seemed like it was different each time).
- I can't figure out how to make newly created pages show up on the frontend of the site.
- Text created in markdown doesn't seem to show up properly (but this also seems like it works inconsistently)

**Comment by pjsier** [comment]
Gotcha, for the changes showing up that should generally take a couple minutes. One workaround for that is that changes should show up a lot quicker on http://documenters-field-guide.netlify.com/ (more of an internal site through the CMS)

We don't have a setup for adding pages to the site menus yet, but I've got an idea for making that work

And any specific examples for markdown? There are a few cases where we had to use some weird markdown to match the Google Doc format

**Comment by diaholliday** [comment]
The markdown checkboxes were showing up as bullet-points on the frontend.

**Comment by pjsier** [comment]
The markdown checkboxes are because "- [ ]" works in the static site builder as a checkbox, but not in the rich text editor. In the markdown editor you'll see it with that notation. They were breaking for some pages because Markdown doesn't support including an extra line break between checkbox items

Updated the content type setup so that there are just categories and pages. Pages are any of the submenu items, Categories are the top level items. You can create a new page and make it show up in the menu by selecting the category you want it to show up in (start typing it and it'll show as an option), and select the switch for "In Menu?"

**Comment by pjsier** [comment]
Assuming this can be closed?
